all: basic

basic: basic.c
	gcc basic.c -g -o basic -lncurses

mouse-keys: mouse-keys.c
	gcc mouse-keys.c -g -o mouse-keys -lcurses

panels: panels.c
	gcc panels.c -g -o panels -lcurses -lpanel

box: box.c
	gcc box.c -g -o box -lcurses
